### ISSUE TITLE
Make VsixTesting.Installer wait for input if there's an exception while installing

### ISSUE THREAD

**Issue by jcansdale** [josetr/VsixTesting#18]
I'm attempting to install for Visual Studio 2017 - Community Preview, but `VsixTesting.Installer` is failing with an exception. The exception flashes for a fraction for a second before vanishing. There doesn't seem to be an obvious way to prevent this.

Could you either add a `/wait` option or make it automatically wait if an exception is thrown? 🙏

**Comment by jcansdale** [comment]
Alternatively, simply calling `Trace.WriteLine(e)` would give me a better chance of tracking down exceptions in the child installer process. 🙂

I wish Visual Studio had the option to automatically debug child processes!

**Comment by josetr** [comment]
I didn't think this feature was needed from the beggining because you could open up a terminal and invoke VsixTesting.Installer.exe with the same arguments to see the exception.

Visual Studio 2019 now let you keep the console window open as well so I don't think this feature is needed anymore. 

I'm closing this due to age but please re-open it if needed.

**Comment by jcansdale** [comment]
> I didn't think this feature was needed from the beggining because you could open up a terminal and invoke VsixTesting.Installer.exe with the same arguments to see the exception.

Thanks for the tip. I didn't think of doing this. 😊
