### ISSUE TITLE
Consider avoiding traits with spaces

### ISSUE THREAD

**Issue by sharwell** [josetr/VsixTesting#3]
Currently the default automatically-assigned traits have spaces in both the key and the value.

https://github.com/josetr/VsixTesting/blob/3cc0e356cbeca90e5e280fc9854edabed1621726/src/VsixTesting.Xunit/Internal/VsTestCaseBase.cs#L61

The use of this form results in cases where command line arguments involving the traits are not obvious.

**Comment by sharwell** [comment]
Context:
https://github.com/tunnelvisionlabs/MouseFastScroll/blob/0fa44df8341068e887a2da92a20718f023f1b339/appveyor.yml#L33

I tried the following so far:

* ``-notrait `"Visual Studio=2012 Exp`"`` (did not work)
* ``-notrait \`"Visual Studio=2012 Exp\`"`` (did not work)
* `-notrait 2012` (pending)

**Comment by sharwell** [comment]
@josetr I haven't found a way to skip a test that only runs on a version of Visual Studio that is not installed. Do you know how this can be done?

**Comment by josetr** [comment]
> The use of this form results in cases where command line arguments involving the traits are not obvious. 

I agree. They are gone now. Now I need to learn to live with an ugly VS Test Explorer.

> I tried the following so far:

The 2nd one was the correct one (for the record)

> I haven't found a way to skip a test that only runs on a version of Visual Studio that is not installed. Do you know how this can be done?

This is not possible because when an exception is thrown during discovery an "ExceptionTestCase" is reported and this test case does not have any traits so you cannot filter it nor skip it because it does not implement the skip functionality.

Can you make a separate issue for this please?

**Comment by sharwell** [comment]
> Can you make a separate issue for this please?

Filed #7
